version: "3"
services:
  web:
    image: juancarlosqr/docker-get-started:part2
    depends_on:
      - redis
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - webnet
networks:
  webnet: