const os = require('os')

console.log(os.constants)
console.log(os.totalmem())
console.log(os.freemem())
console.log(os.userInfo())
console.log(os.uptime())
console.log(os.arch())
console.log(os.cpus())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.loadavg())
console.log(os.networkInterfaces())
console.log(os.platform())
console.log(os.release())
console.log(os.tmpdir())
console.log(os.type())
